sudo: false
language: node_js
node_js:
- 9

before_script:
- npm i

script:
- npm run lint
- npm run test
- npm run prod

cache:
  directories:
  - node_modules

aliases:
  deploy: &deploy
    provider: heroku
    api_key:
      secure: b266e2a8-bcab-4e52-94f7-ae0f6b60dc58
    skip_cleanup: true

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
      deploy:
        <<: *deploy
        app: node-git-development
        on:
          all_branches: true

    - stage: Deploy (production)
      if: tag IS present
      deploy:
        <<: *deploy
        app: node-git-production
        on:
          tags: true
          all_branches: true
build:
  docker:
    web: Dockerfile